### ISSUE TITLE
Does not cleanly start under Address Sanitizer

### ISSUE THREAD

**Issue by neuschaefer** [sebastianbiallas/ht#5]
HTE d462d620d does not cleanly start when compiled with [Address Sanitizer](http://clang.llvm.org/docs/AddressSanitizer.html). The following output is produced:

```
=================================================================
==7327==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00000125f9b8 at pc 0x00000089e45e bp 0x7fffc9635790 sp 0x7fffc9635788
READ of size 8 at 0x00000125f9b8 thread T0
    #0 0x89e45d in find_pal_layout(pal_class*, char const*, int*) /home/jn/dev/hack/ht/htpal.cc:166:3
    #1 0x89f059 in load_pal(char const*, char const*, palette*) /home/jn/dev/hack/ht/htpal.cc:191:19
    #2 0x9fe6bd in ht_c_syntax_lexer::reloadpalette() /home/jn/dev/hack/ht/syntax.cc:432:2
    #3 0x9fe46c in ht_c_syntax_lexer::config_changed() /home/jn/dev/hack/ht/syntax.cc:375:2
    #4 0x9fdc6d in ht_c_syntax_lexer::init() /home/jn/dev/hack/ht/syntax.cc:363:2
    #5 0x651a39 in ht_app::init(Bounds*) /home/jn/dev/hack/ht/htapp.cc:1430:2
    #6 0x685460 in init_app() /home/jn/dev/hack/ht/htapp.cc:3364:2
    #7 0x995ba2 in init() /home/jn/dev/hack/ht/main.cc:98:8
    #8 0x98fce0 in main /home/jn/dev/hack/ht/main.cc:282:7
    #9 0x7f34911dcb44 in __libc_start_main /build/glibc-NmptCx/glibc-2.19/csu/libc-start.c:287
    #10 0x53624c in _start (/home/jn/dev/hack/ht/ht+0x53624c)

0x00000125f9b8 is located 40 bytes to the left of global variable 'pal_layout_analyser' defined in 'htpal.cc:118:12' (0x125f9e0) of size 96
0x00000125f9b8 is located 8 bytes to the right of global variable 'pal_layout_syntax' defined in 'htpal.cc:103:12' (0x125f900) of size 176
SUMMARY: AddressSanitizer: global-buffer-overflow /home/jn/dev/hack/ht/htpal.cc:166 find_pal_layout(pal_class*, char const*, int*)
Shadow bytes around the buggy address:
  0x000080243ee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080243ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080243f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080243f10: 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080243f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x000080243f30: 00 00 00 00 00 00 f9[f9]f9 f9 f9 f9 00 00 00 00
  0x000080243f40: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x000080243f50: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x000080243f60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080243f70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080243f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  ASan internal:           fe
==7327==ABORTING
```

ASan is nice because it helps in testing crash bugs.

**Comment by sebastianbiallas** [comment]
Thanks. Should be fixed in master.

**Comment by neuschaefer** [comment]
Thanks for fixing.
I have a few ELF files that ht crashes on, should I report them here or via email?

**Comment by sebastianbiallas** [comment]
Send them by email, thanks.
